### ISSUE TITLE
[BUG] Route method is not overriding

### ISSUE THREAD

**Issue by Giovanny-DS** [adrien2p/medusa-extender#110]
**Describe the bug**
The route method is not overriding, or I'm doing it wrong but can't find anything besides the marketplace example.

**To Reproduce**
1. You can go and install https://github.com/Giovanny-DS/sharedbackend
2. Run it, and check that admin/auth is not overriding the handler.
3. You may also just go and check the auth module code that I did write. 

**Expected behavior**
we should receive a JSON like
`{ user: cleanRes, test: 'test' }`

instead of just 
`{ user: cleanRes }`

**Screenshots**
not applicable?

**Package version:**
 - Version 1.7.2

**Additional context**
I think all it's clear, but I can answer any question fast.

**Comment by adrien2p** [comment]
Hi there, could you set the requireAuth to false and add the authenticate middleware from medusa before your handler.

Those routes are not meant to be overridden originally but you can achieve that the way i gave you above. In the future, it is likely that those routes will call an auth strategy instead of being implemented. Which means that when it will happen, you will likely have to update the strategy to return what you want. But at the moment, this is the way to do it 💪

Let me know ☺️

**Comment by Giovanny-DS** [comment]
Thanks, I'll try it out. and give feedback.
I assume it would works since the docs say we can add and override routes.

**Comment by adrien2p** [comment]
You can just use the one provided by medusa (authenticate). 

Yes you can still override it

**Comment by Giovanny-DS** [comment]
Just got it working!!. thanks!!
